[workspace]
members = [ "di", "orm", "schema_reader", "utils"]
resolver = "2"



[workspace.dependencies]
di = { path = "./di" }
orm = { path = "./orm" }
schema_reader = { path = "./schema_reader" }
utils = { path = "./utils" }
